### ISSUE TITLE
[QST] Out of interest is this project active

### ISSUE THREAD

**Issue by Sh4zKh4n** [rapidsai/dask-cugraph#34]
Is this project active or is it mature enough it worked or is this not the case anymore?

**Comment by afender** [comment]
Hi @Sh4zKh4n, the features developed in this repo (and more) have been added to the main cuGraph repository.: https://github.com/rapidsai/cugraph
Here is more information on the multi-GPU features and Dask interaction: https://docs.rapids.ai/api/cugraph/nightly/dask-cugraph.html

**Comment by Sh4zKh4n** [comment]
@afender thanks that's really helpful.
